# Generated by Django 4.0 on 2022-01-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0002_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=30, null=True)),
                ('psswd', models.CharField(max_length=12, null=True)),
            ],
        ),
    ]
