# Generated by Django 4.0 on 2022-01-27 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0003_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='age',
            field=models.IntegerField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='mob',
            field=models.IntegerField(max_length=11, null=True),
        ),
    ]
