# Generated by Django 4.0 on 2022-01-27 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0004_users_age_users_mob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='psswd',
            field=models.IntegerField(max_length=20, null=True),
        ),
    ]
