# Generated by Django 4.0 on 2022-01-27 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0005_alter_users_psswd'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='age',
            field=models.DateField(max_length=30, null=True),
        ),
    ]
