# Generated by Django 4.0 on 2022-01-28 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0007_category_program'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='phone',
        ),
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.DateField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mob',
            field=models.IntegerField(max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='psswd',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='cu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='users',
        ),
    ]
