# Generated by Django 4.0 on 2022-01-29 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0008_remove_user_phone_user_age_user_mob_user_psswd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='cu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.category'),
        ),
    ]
