# Generated by Django 4.0 on 2022-01-31 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0010_alter_category_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='classes',
            new_name='Episode',
        ),
        migrations.AlterField(
            model_name='category',
            name='valid',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='image',
            field=models.ImageField(null=True, upload_to='image/'),
        ),
    ]
