# Generated by Django 4.0 on 2022-01-31 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0011_rename_classes_program_episode_alter_category_valid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='cu',
            new_name='ca',
        ),
    ]
