# Generated by Django 4.0 on 2022-02-21 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0013_alter_user_mob_alter_user_psswd'),
    ]

    operations = [
        migrations.CreateModel(
            name='maincategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caname', models.CharField(max_length=40, null=True)),
                ('price', models.IntegerField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='category',
            name='price',
        ),
        migrations.AddField(
            model_name='category',
            name='cat',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.maincategory'),
        ),
    ]
