# Generated by Django 4.0 on 2022-02-22 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0014_maincategory_remove_category_price_category_cat'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='video',
            field=models.FileField(null=True, upload_to='video/'),
        ),
    ]
