# Generated by Django 4.0 on 2022-02-23 05:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0015_program_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(null=True)),
                ('validate', models.BooleanField()),
                ('ct', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.category')),
                ('us', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.user')),
            ],
        ),
    ]
