# Generated by Django 4.0 on 2022-02-23 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0016_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='psswd',
        ),
    ]
