# Generated by Django 4.0 on 2022-02-23 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0017_remove_user_psswd'),
    ]

    operations = [
        migrations.AddField(
            model_name='maincategory',
            name='valid',
            field=models.DateField(null=True),
        ),
    ]
