# Generated by Django 3.2.9 on 2022-04-25 13:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0018_maincategory_valid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ct',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='MainApp.maincategory'),
        ),
        migrations.AlterField(
            model_name='order',
            name='validate',
            field=models.BooleanField(null=True),
        ),
    ]
