# Generated by Django 3.2.9 on 2022-04-25 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0020_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='validate',
        ),
        migrations.AddField(
            model_name='order',
            name='validity',
            field=models.DateField(null=True),
        ),
    ]
