# Generated by Django 4.0.4 on 2022-05-13 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0021_auto_20220425_1926'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='video',
            new_name='videofile',
        ),
    ]
