# Generated by Django 4.0.4 on 2022-05-13 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0022_rename_video_program_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='videofile',
            field=models.FileField(null=True, upload_to='videos/'),
        ),
    ]
