# Generated by Django 4.0.4 on 2022-05-13 05:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0023_alter_program_videofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='videofile',
            new_name='video',
        ),
    ]
