# Generated by Django 4.0.4 on 2022-05-13 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0024_rename_videofile_program_video'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='video',
            new_name='videofile',
        ),
    ]
