# Generated by Django 4.0.4 on 2022-05-13 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MainApp', '0025_rename_video_program_videofile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='videofile',
        ),
        migrations.AddField(
            model_name='program',
            name='video',
            field=models.FileField(null=True, upload_to='video/'),
        ),
    ]
